# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import QSS_Resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 560)
        MainWindow.setStyleSheet("/* Main app setup*/\n"
"*{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    background: transparent;\n"
"    padding: 0;\n"
"    margin: 0;\n"
"    color: #fff;\n"
"}\n"
"\n"
"/* Main app background*/\n"
"#centralwidget{\n"
"    background-color: #4e4d51;\n"
"}\n"
"\n"
"/*Left Menu selection */\n"
"#leftMenuSubContainer{\n"
"    background-color: #2D2E2E;\n"
"    border-radius: 0px;\n"
"}\n"
"#leftMenuSubContainer QPushButton{\n"
"    border-top-left-radius: 4px;\n"
"    border-bottom-left-radius: 4px;\n"
"}\n"
"\n"
"/* Left Menu*/\n"
"#frame, #frame_4, #frame_5{\n"
"    background-color: #606390;\n"
"    border-radius:0px\n"
"}\n"
"#widget{\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #606390, stop: 1 #36384d);\n"
"}\n"
"/* Left Minimized Menu */\n"
"#minimizedMenuSubContainer{\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #606390, stop: 1 #36384d);\n"
"    border-radius:0px\n"
"}\n"
"\n"
"/* Right Menu*/\n"
"#rightMenuSubContainer{\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #606390, stop: 1 #36384d);\n"
"    border-radius:0px\n"
"}\n"
"/* TerminalPages*/\n"
"#page_12, #page_13{\n"
"    background-color: #2d2e2e;\n"
"    border-radius:4px\n"
"}\n"
"/* Terminal*/\n"
"#terminalFrame{\n"
"    background-color: #2d2e2e;\n"
"    border-radius:4px\n"
"}\n"
"#terminalInputFrame{\n"
"    background: #2d2e2e;\n"
"    border-radius: 4px;\n"
"}\n"
"#terminalInput{\n"
"    padding: 4 8px;\n"
"    \n"
"    selection-background-color: darkgray;\n"
"}\n"
"\n"
"/* Right Minimized Menu*/\n"
"#minRightMenuSubContainer{\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #606390, stop: 1 #36384d);\n"
"    border-radius:0px\n"
"}\n"
"\n"
"/* Editor Tabs and scrollbar*/\n"
"QTabBar::tab {\n"
"    background: #2D2E2E;\n"
"\n"
"    border-bottom-color: #C2C7CB; /* same as the pane color */\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    min-width: 10ex;\n"
"    padding: 5px 5px;\n"
"}\n"
"QTabBar::close-button {\n"
"    image: url(:/icons/Icons/window_close.png);\n"
"    margin-right:4px;\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background: #4c8096;\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    width: 6px;\n"
"    margin: 15px 0 15px 0px;\n"
"    background-color: transparent;\n"
"    border-radius 0px;\n"
"}\n"
"QScrollBar:handle:vertical {\n"
"    background-color: #4c8096;\n"
"    border-radius: 3px;\n"
"}\n"
"QScrollBar:handle:vertical:pressed {\n"
"    background-color: #73e0ee;\n"
"}\n"
"QScrollBar::sub-line::vertical {\n"
"    border: none;\n"
"    background: none;\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line::vertical {\n"
"    border: none;\n"
"    background: none;\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"/* horizontal scrollbar*/\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    height: 6px;\n"
"    margin: 0px 15px 0px 15px;\n"
"    background-color: transparent;\n"
"    border-radius 0px;\n"
"}\n"
"QScrollBar:handle:horizontall {\n"
"    background-color: #4c8096;\n"
"    border-radius: 3px;\n"
"}\n"
"QScrollBar:handle:horizontal:pressed {\n"
"    background-color: #73e0ee;\n"
"}\n"
"QScrollBar::sub-line::horizontal {\n"
"    border: none;\n"
"    background: none;\n"
"    width: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line::horizontal {\n"
"    border: none;\n"
"    background: none;\n"
"    width: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"/* QsciSintilla editor*/\n"
"QsciScintilla {\n"
"    border: none;\n"
"    background-color: #282c34;\n"
"    color: #D3D3D3;\n"
"}\n"
"\n"
"/* Search Bar*/\n"
"#lineEdit {\n"
"    border: 1px solid;\n"
"    border-color: #baacfd;    \n"
"    border-radius: 5px;\n"
"    padding: 2 8px;\n"
"    background: #2d2e2e;\n"
"    selection-background-color: darkgray;\n"
"}\n"
"\n"
"/* */\n"
"QListWidget {\n"
"            background-color: #2d2e2e;\n"
"            border-radius: 5px;\n"
"            border: 1px solid #baacfd;\n"
"            padding: 5px;\n"
"            color: #D3D3D3;\n"
"}\n"
"\n"
"/* */\n"
"QCheckBox {\n"
"    spacing: 5px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"/* Tree view*/\n"
"QTreeView::item {\n"
"    border-top-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"}\n"
"QTreeView::item:hover{\n"
"    background-color: #8680a6;\n"
"    border-radius: 2px;\n"
"}\n"
"QTreeView::item:selected{\n"
"    background-color: #9287c5;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"/* */\n"
"#openPerformanceMonitorBtn {\n"
"    background: #8680A6;\n"
"    border-radius: 4px;\n"
"}\n"
"#openPerformanceMonitorBtn::hover {\n"
"    background: #9287c5;\n"
"}\n"
"#openPerformanceMonitorMinBtn {\n"
"    background: #8680A6;\n"
"    border-radius: 4px;\n"
"}\n"
"#openPerformanceMonitorMinBtn::hover {\n"
"    background: #9287c5;\n"
"}\n"
"\n"
"/* AI Chat assistant*/\n"
"/* bottom chat*/\n"
"#lineEdit_2{\n"
"    padding: 4 8px;\n"
"    background: #2d2e2e;\n"
"    selection-background-color: darkgray;\n"
"}\n"
"#addBtn{\n"
"    background: #8680A6;\n"
"    border-radius: 14px;\n"
"}\n"
"#addBtn:hover{\n"
"    background: #9287c5;\n"
"}\n"
"#bottomChat{\n"
"    background: #2d2e2e;\n"
"    border-radius: 17.4px;\n"
"}\n"
"#sendBtn{\n"
"    background: #8680A6;\n"
"    border-radius: 14px;\n"
"}\n"
"#sendBtn:hover{\n"
"    background: #9287c5;\n"
"}\n"
"#backBtn{\n"
"    background: #8680A6;\n"
"    border-radius: 14px;\n"
"}\n"
"#backBtn:hover{\n"
"    background: #9287c5;\n"
"}\n"
"/* chatLog*/\n"
"#MessagesWidget {\n"
"    background: transparent;\n"
"}\n"
"/* Menu bar*/\n"
"QMenuBar{\n"
"    background-color: #2D2E2E;\n"
"    padding-top: 6px;\n"
"    spacing: 6px;\n"
"}\n"
"QMenuBar::item:selected {\n"
"    background: #606390;\n"
"    border-radius: 2px;\n"
"}\n"
"QMenu{\n"
"     background-color: #2D2E2E;\n"
"     margin: 2px; /* some spacing around the menu */\n"
"}\n"
"QMenu::item {\n"
"    padding: 4px 25px 4px 20px;\n"
"    border: 1px solid transparent; /* reserve space for selection border */\n"
"}\n"
"QMenu::item:selected {\n"
"    background: #606390;\n"
"    border-radius: 2px;\n"
"}\n"
"QMenu::separator{\n"
"    border: 1px transparent;\n"
"    height: 1px;\n"
"    background: #baacfd;\n"
"    margin-left: 10px;\n"
"    margin-right: 5px;\n"
"    margin-top: 5px;\n"
"    margin-bottom: 4px;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftMenuContainer = QtWidgets.QWidget(parent=self.centralwidget)
        self.leftMenuContainer.setObjectName("leftMenuContainer")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.leftMenuContainer)
        self.verticalLayout.setContentsMargins(0, 3, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.leftMenuSubContainer = QtWidgets.QWidget(parent=self.leftMenuContainer)
        self.leftMenuSubContainer.setMinimumSize(QtCore.QSize(50, 0))
        self.leftMenuSubContainer.setObjectName("leftMenuSubContainer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.leftMenuSubContainer)
        self.verticalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(parent=self.leftMenuSubContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.homeBtn = QtWidgets.QPushButton(parent=self.frame_2)
        self.homeBtn.setMinimumSize(QtCore.QSize(0, 40))
        self.homeBtn.setStyleSheet("background-color: #606390;")
        self.homeBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Icons/home.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.homeBtn.setIcon(icon)
        self.homeBtn.setIconSize(QtCore.QSize(24, 24))
        self.homeBtn.setObjectName("homeBtn")
        self.verticalLayout_4.addWidget(self.homeBtn)
        self.fileBtn = QtWidgets.QPushButton(parent=self.frame_2)
        self.fileBtn.setMinimumSize(QtCore.QSize(0, 40))
        self.fileBtn.setStyleSheet("")
        self.fileBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Icons/folder.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.fileBtn.setIcon(icon1)
        self.fileBtn.setIconSize(QtCore.QSize(24, 24))
        self.fileBtn.setObjectName("fileBtn")
        self.verticalLayout_4.addWidget(self.fileBtn)
        self.searchBtn = QtWidgets.QPushButton(parent=self.frame_2)
        self.searchBtn.setMinimumSize(QtCore.QSize(0, 40))
        self.searchBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/Icons/search.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.searchBtn.setIcon(icon2)
        self.searchBtn.setIconSize(QtCore.QSize(24, 24))
        self.searchBtn.setObjectName("searchBtn")
        self.verticalLayout_4.addWidget(self.searchBtn)
        self.aiBtn = QtWidgets.QPushButton(parent=self.frame_2)
        self.aiBtn.setMinimumSize(QtCore.QSize(0, 40))
        self.aiBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/Icons/codesandbox.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.aiBtn.setIcon(icon3)
        self.aiBtn.setIconSize(QtCore.QSize(24, 24))
        self.aiBtn.setObjectName("aiBtn")
        self.verticalLayout_4.addWidget(self.aiBtn)
        self.verticalLayout_2.addWidget(self.frame_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.frame_3 = QtWidgets.QFrame(parent=self.leftMenuSubContainer)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.settingsBtn = QtWidgets.QPushButton(parent=self.frame_3)
        self.settingsBtn.setMinimumSize(QtCore.QSize(0, 40))
        self.settingsBtn.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.settingsBtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/Icons/settings.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.settingsBtn.setIcon(icon4)
        self.settingsBtn.setIconSize(QtCore.QSize(24, 24))
        self.settingsBtn.setObjectName("settingsBtn")
        self.verticalLayout_5.addWidget(self.settingsBtn)
        self.verticalLayout_2.addWidget(self.frame_3, 0, QtCore.Qt.AlignmentFlag.AlignBottom)
        self.verticalLayout.addWidget(self.leftMenuSubContainer, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.horizontalLayout.addWidget(self.leftMenuContainer, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.minimizedMenuContainer = QCustomSlideMenu(parent=self.centralwidget)
        self.minimizedMenuContainer.setMinimumSize(QtCore.QSize(50, 0))
        self.minimizedMenuContainer.setObjectName("minimizedMenuContainer")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.minimizedMenuContainer)
        self.verticalLayout_12.setContentsMargins(0, 3, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.minimizedMenuSubContainer = QtWidgets.QWidget(parent=self.minimizedMenuContainer)
        self.minimizedMenuSubContainer.setMinimumSize(QtCore.QSize(50, 0))
        self.minimizedMenuSubContainer.setObjectName("minimizedMenuSubContainer")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.minimizedMenuSubContainer)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_4 = QtWidgets.QFrame(parent=self.minimizedMenuSubContainer)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.maxCenterMenuBtn = QtWidgets.QPushButton(parent=self.frame_4)
        self.maxCenterMenuBtn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/Icons/chevron-right.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.maxCenterMenuBtn.setIcon(icon5)
        self.maxCenterMenuBtn.setIconSize(QtCore.QSize(24, 24))
        self.maxCenterMenuBtn.setObjectName("maxCenterMenuBtn")
        self.horizontalLayout_3.addWidget(self.maxCenterMenuBtn, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.verticalLayout_14.addWidget(self.frame_4, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.minCenterMenuPages = QCustomStackedWidget(parent=self.minimizedMenuSubContainer)
        self.minCenterMenuPages.setMinimumSize(QtCore.QSize(0, 0))
        self.minCenterMenuPages.setMaximumSize(QtCore.QSize(50, 16777215))
        self.minCenterMenuPages.setObjectName("minCenterMenuPages")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_5 = QtWidgets.QLabel(parent=self.page_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        self.label_5.setFont(font)
        self.label_5.setScaledContents(False)
        self.label_5.setWordWrap(True)
        self.label_5.setIndent(0)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_15.addWidget(self.label_5)
        self.minCenterMenuPages.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.page_6.setObjectName("page_6")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.page_6)
        self.verticalLayout_13.setContentsMargins(3, 0, 3, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_14 = QtWidgets.QFrame(parent=self.page_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_14.sizePolicy().hasHeightForWidth())
        self.frame_14.setSizePolicy(sizePolicy)
        self.frame_14.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_14.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_14.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_50 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_50.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout_50.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_50.setSpacing(1)
        self.verticalLayout_50.setObjectName("verticalLayout_50")
        self.label = QtWidgets.QLabel(parent=self.frame_14)
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_50.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.TextToText = QtWidgets.QComboBox(parent=self.frame_14)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.TextToText.setFont(font)
        self.TextToText.setStyleSheet("#TextToText{\n"
"    background-color: #8680A6;\n"
"    border: 1px #8680A6;\n"
"    border-radius: 4px;\n"
"}\n"
"#TextToText::hover{\n"
"    background-color: #9287c5;\n"
"}\n"
"#TextToText::on {\n"
"    background-color: #9287c5;\n"
"}\n"
"\n"
"#TextToText QListView {\n"
"    background-color: #2D2E2E;\n"
"    \n"
"}\n"
"#TextToText QListView:item {\n"
"    border: 1px solid transparent; /* reserve space for selection border */\n"
"    \n"
"}\n"
"#TextToText QListView:item:hover {\n"
"    background: #606390;\n"
"    border-radius: 2px;\n"
"    \n"
"}\n"
"#TextToText::down-arrow {\n"
"    image: none;\n"
"}\n"
"#TextToText::drop-down { \n"
"                      subcontrol-origin: padding; \n"
"                      subcontrol-position: top right; \n"
"                      width: 15px; \n"
"                      border-left-width: 1px; \n"
"                      border-left-color: transparent; \n"
"                      border-left-style: solid; /* just a single line */\n"
"                      border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"                      border-bottom-right-radius: 3px; \n"
"}\n"
"")
        self.TextToText.setObjectName("TextToText")
        self.TextToText.addItem("")
        self.TextToText.addItem("")
        self.TextToText.addItem("")
        self.TextToText.addItem("")
        self.verticalLayout_50.addWidget(self.TextToText)
        self.verticalLayout_13.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(parent=self.page_6)
        self.frame_15.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_15.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_51 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_51.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_51.setSpacing(0)
        self.verticalLayout_51.setObjectName("verticalLayout_51")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_15)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_51.addWidget(self.label_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.CodeToCode = QtWidgets.QComboBox(parent=self.frame_15)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.CodeToCode.setFont(font)
        self.CodeToCode.setStyleSheet("#CodeToCode{\n"
"    background-color: #8680A6;\n"
"    border: 1px #8680A6;\n"
"    border-radius: 4px;\n"
"}\n"
"#CodeToCode::hover{\n"
"    background-color: #9287c5;\n"
"}\n"
"#CodeToCode::on {\n"
"    background-color: #9287c5;\n"
"}\n"
"\n"
"#CodeToCode QListView {\n"
"    background-color: #2D2E2E;\n"
"    \n"
"}\n"
"#CodeToCode QListView:item {\n"
"    border: 1px solid transparent; /* reserve space for selection border */\n"
"    \n"
"}\n"
"#CodeToCode QListView:item:hover {\n"
"    background: #606390;\n"
"    border-radius: 2px;\n"
"    \n"
"}\n"
"#CodeToCode::down-arrow {\n"
"    image: none;\n"
"}\n"
"#CodeToCode::drop-down { \n"
"                      subcontrol-origin: padding; \n"
"                      subcontrol-position: top right; \n"
"                      width: 15px; \n"
"                      border-left-width: 1px; \n"
"                      border-left-color: transparent; \n"
"                      border-left-style: solid; /* just a single line */\n"
"                      border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"                      border-bottom-right-radius: 3px; \n"
"}\n"
"")
        self.CodeToCode.setObjectName("CodeToCode")
        self.CodeToCode.addItem("")
        self.CodeToCode.addItem("")
        self.CodeToCode.addItem("")
        self.CodeToCode.addItem("")
        self.verticalLayout_51.addWidget(self.CodeToCode, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.verticalLayout_13.addWidget(self.frame_15)
        self.frame_16 = QtWidgets.QFrame(parent=self.page_6)
        self.frame_16.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_16.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_52 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_52.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_52.setSpacing(4)
        self.verticalLayout_52.setObjectName("verticalLayout_52")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_16)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_52.addWidget(self.label_3, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.Summerize = QtWidgets.QComboBox(parent=self.frame_16)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.Summerize.setFont(font)
        self.Summerize.setStyleSheet("#Summerize{\n"
"    background-color: #8680A6;\n"
"    border: 1px #8680A6;\n"
"    border-radius: 4px;\n"
"}\n"
"#Summerize::hover{\n"
"    background-color: #9287c5;\n"
"}\n"
"#Summerize::on {\n"
"    background-color: #9287c5;\n"
"}\n"
"\n"
"#Summerize QListView {\n"
"    background-color: #2D2E2E;\n"
"    \n"
"}\n"
"#Summerize QListView:item {\n"
"    border: 1px solid transparent; /* reserve space for selection border */\n"
"    \n"
"}\n"
"#Summerize QListView:item:hover {\n"
"    background: #606390;\n"
"    border-radius: 2px;\n"
"    \n"
"}\n"
"#Summerize::down-arrow {\n"
"    image: none;\n"
"}\n"
"#Summerize::drop-down { \n"
"                      subcontrol-origin: padding; \n"
"                      subcontrol-position: top right; \n"
"                      width: 15px; \n"
"                      border-left-width: 1px; \n"
"                      border-left-color: transparent; \n"
"                      border-left-style: solid; /* just a single line */\n"
"                      border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"                      border-bottom-right-radius: 3px; \n"
"}\n"
"")
        self.Summerize.setObjectName("Summerize")
        self.Summerize.addItem("")
        self.Summerize.addItem("")
        self.Summerize.addItem("")
        self.Summerize.addItem("")
        self.verticalLayout_52.addWidget(self.Summerize, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.verticalLayout_13.addWidget(self.frame_16)
        self.minCenterMenuPages.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.page_7)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_7 = QtWidgets.QLabel(parent=self.page_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        self.label_7.setFont(font)
        self.label_7.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label_7.setScaledContents(False)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_16.addWidget(self.label_7)
        self.minCenterMenuPages.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.page_8)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_8 = QtWidgets.QLabel(parent=self.page_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        self.label_8.setFont(font)
        self.label_8.setScaledContents(False)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_17.addWidget(self.label_8)
        self.minCenterMenuPages.addWidget(self.page_8)
        self.verticalLayout_14.addWidget(self.minCenterMenuPages)
        self.verticalLayout_12.addWidget(self.minimizedMenuSubContainer, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.horizontalLayout.addWidget(self.minimizedMenuContainer)
        self.centerMenuContainer = QCustomSlideMenu(parent=self.centralwidget)
        self.centerMenuContainer.setMinimumSize(QtCore.QSize(200, 0))
        self.centerMenuContainer.setObjectName("centerMenuContainer")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centerMenuContainer)
        self.verticalLayout_3.setContentsMargins(0, 3, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(parent=self.centerMenuContainer)
        self.widget.setObjectName("widget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame = QtWidgets.QFrame(parent=self.widget)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 42))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.centerMenuLabels = QtWidgets.QStackedWidget(parent=self.frame)
        self.centerMenuLabels.setObjectName("centerMenuLabels")
        self.page_18 = QtWidgets.QWidget()
        self.page_18.setObjectName("page_18")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout(self.page_18)
        self.verticalLayout_35.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_35.setSpacing(0)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.label_19 = QtWidgets.QLabel(parent=self.page_18)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_35.addWidget(self.label_19)
        self.centerMenuLabels.addWidget(self.page_18)
        self.page_19 = QtWidgets.QWidget()
        self.page_19.setObjectName("page_19")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout(self.page_19)
        self.verticalLayout_37.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_37.setSpacing(0)
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.label_22 = QtWidgets.QLabel(parent=self.page_19)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_37.addWidget(self.label_22)
        self.centerMenuLabels.addWidget(self.page_19)
        self.page_20 = QtWidgets.QWidget()
        self.page_20.setObjectName("page_20")
        self.verticalLayout_38 = QtWidgets.QVBoxLayout(self.page_20)
        self.verticalLayout_38.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_38.setSpacing(0)
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.label_23 = QtWidgets.QLabel(parent=self.page_20)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_38.addWidget(self.label_23)
        self.centerMenuLabels.addWidget(self.page_20)
        self.page_21 = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(13)
        self.page_21.setFont(font)
        self.page_21.setObjectName("page_21")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout(self.page_21)
        self.verticalLayout_36.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_36.setSpacing(0)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.label_24 = QtWidgets.QLabel(parent=self.page_21)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_36.addWidget(self.label_24)
        self.centerMenuLabels.addWidget(self.page_21)
        self.horizontalLayout_2.addWidget(self.centerMenuLabels, 0, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.minCenterMenuBtn = QtWidgets.QPushButton(parent=self.frame)
        self.minCenterMenuBtn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/Icons/chevron-left.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.minCenterMenuBtn.setIcon(icon6)
        self.minCenterMenuBtn.setIconSize(QtCore.QSize(24, 24))
        self.minCenterMenuBtn.setObjectName("minCenterMenuBtn")
        self.horizontalLayout_2.addWidget(self.minCenterMenuBtn, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.verticalLayout_6.addWidget(self.frame, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.centerMenuPages = QCustomStackedWidget(parent=self.widget)
        self.centerMenuPages.setObjectName("centerMenuPages")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.settingsDescription = QtWidgets.QLabel(parent=self.page)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.settingsDescription.setFont(font)
        self.settingsDescription.setObjectName("settingsDescription")
        self.verticalLayout_7.addWidget(self.settingsDescription, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.line = QtWidgets.QFrame(parent=self.page)
        font = QtGui.QFont()
        font.setBold(False)
        self.line.setFont(font)
        self.line.setAcceptDrops(False)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_7.addWidget(self.line)
        self.frame_8 = QtWidgets.QFrame(parent=self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.frame_9 = QtWidgets.QFrame(parent=self.frame_8)
        self.frame_9.setGeometry(QtCore.QRect(60, 30, 120, 80))
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.pushButton = QtWidgets.QPushButton(parent=self.frame_9)
        self.pushButton.setGeometry(QtCore.QRect(40, 20, 75, 24))
        self.pushButton.setObjectName("pushButton")
        self.frame_10 = QtWidgets.QFrame(parent=self.frame_8)
        self.frame_10.setGeometry(QtCore.QRect(60, 150, 120, 80))
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName("frame_10")
        self.comboBox = QtWidgets.QComboBox(parent=self.frame_10)
        self.comboBox.setGeometry(QtCore.QRect(40, 30, 67, 22))
        self.comboBox.setObjectName("comboBox")
        self.frame_17 = QtWidgets.QFrame(parent=self.frame_8)
        self.frame_17.setGeometry(QtCore.QRect(60, 290, 120, 80))
        self.frame_17.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_7.addWidget(self.frame_8)
        self.centerMenuPages.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_45 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_45.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_45.setObjectName("verticalLayout_45")
        self.widget_3 = QtWidgets.QWidget(parent=self.page_2)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_44 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_44.setContentsMargins(3, -1, 3, 3)
        self.verticalLayout_44.setObjectName("verticalLayout_44")
        self.chatMessages = QtWidgets.QScrollArea(parent=self.widget_3)
        self.chatMessages.setWidgetResizable(True)
        self.chatMessages.setObjectName("chatMessages")
        self.messagesWidget = QtWidgets.QWidget()
        self.messagesWidget.setGeometry(QtCore.QRect(0, 0, 194, 409))
        self.messagesWidget.setObjectName("messagesWidget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.messagesWidget)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_9.addItem(spacerItem1)
        self.frame_12 = QtWidgets.QFrame(parent=self.messagesWidget)
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_46 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_46.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_46.setSpacing(0)
        self.verticalLayout_46.setObjectName("verticalLayout_46")
        self.verticalLayout_9.addWidget(self.frame_12)
        self.chatMessages.setWidget(self.messagesWidget)
        self.verticalLayout_44.addWidget(self.chatMessages)
        self.bottomChat = QtWidgets.QFrame(parent=self.widget_3)
        self.bottomChat.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.bottomChat.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.bottomChat.setObjectName("bottomChat")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.bottomChat)
        self.horizontalLayout_6.setContentsMargins(4, 3, 3, 3)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.bottomChat)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_6.addWidget(self.lineEdit_2)
        self.addBtn = QtWidgets.QPushButton(parent=self.bottomChat)
        self.addBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.addBtn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/Icons/plus.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.addBtn.setIcon(icon7)
        self.addBtn.setIconSize(QtCore.QSize(22, 22))
        self.addBtn.setObjectName("addBtn")
        self.horizontalLayout_6.addWidget(self.addBtn)
        self.verticalLayout_44.addWidget(self.bottomChat)
        self.verticalLayout_45.addWidget(self.widget_3)
        self.centerMenuPages.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_10.addWidget(self.lineEdit, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.checkBox = QtWidgets.QCheckBox(parent=self.page_3)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_10.addWidget(self.checkBox)
        self.listWidget_2 = QtWidgets.QListWidget(parent=self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_2.sizePolicy().hasHeightForWidth())
        self.listWidget_2.setSizePolicy(sizePolicy)
        self.listWidget_2.setMinimumSize(QtCore.QSize(200, 422))
        self.listWidget_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.listWidget_2.setObjectName("listWidget_2")
        self.verticalLayout_10.addWidget(self.listWidget_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.centerMenuPages.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_11.setContentsMargins(12, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.centerMenuPages.addWidget(self.page_4)
        self.page_22 = QtWidgets.QWidget()
        self.page_22.setObjectName("page_22")
        self.verticalLayout_47 = QtWidgets.QVBoxLayout(self.page_22)
        self.verticalLayout_47.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_47.setObjectName("verticalLayout_47")
        self.frame_11 = QtWidgets.QFrame(parent=self.page_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_11.sizePolicy().hasHeightForWidth())
        self.frame_11.setSizePolicy(sizePolicy)
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_48 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_48.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout_48.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_48.setSpacing(0)
        self.verticalLayout_48.setObjectName("verticalLayout_48")
        self.verticalLayout_47.addWidget(self.frame_11)
        self.frame_13 = QtWidgets.QFrame(parent=self.page_22)
        self.frame_13.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_7.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.backBtn = QtWidgets.QPushButton(parent=self.frame_13)
        self.backBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.backBtn.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/Icons/corner-down-left.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.backBtn.setIcon(icon8)
        self.backBtn.setIconSize(QtCore.QSize(20, 20))
        self.backBtn.setObjectName("backBtn")
        self.horizontalLayout_7.addWidget(self.backBtn)
        self.sendBtn = QtWidgets.QPushButton(parent=self.frame_13)
        self.sendBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.sendBtn.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/Icons/send.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.sendBtn.setIcon(icon9)
        self.sendBtn.setIconSize(QtCore.QSize(20, 20))
        self.sendBtn.setObjectName("sendBtn")
        self.horizontalLayout_7.addWidget(self.sendBtn)
        self.verticalLayout_47.addWidget(self.frame_13, 0, QtCore.Qt.AlignmentFlag.AlignBottom)
        self.centerMenuPages.addWidget(self.page_22)
        self.verticalLayout_6.addWidget(self.centerMenuPages)
        self.verticalLayout_3.addWidget(self.widget)
        self.horizontalLayout.addWidget(self.centerMenuContainer, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.mainBodyContainer = QtWidgets.QWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainBodyContainer.sizePolicy().hasHeightForWidth())
        self.mainBodyContainer.setSizePolicy(sizePolicy)
        self.mainBodyContainer.setStyleSheet("")
        self.mainBodyContainer.setObjectName("mainBodyContainer")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.mainBodyContainer)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.mainBodyContent = QtWidgets.QWidget(parent=self.mainBodyContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainBodyContent.sizePolicy().hasHeightForWidth())
        self.mainBodyContent.setSizePolicy(sizePolicy)
        self.mainBodyContent.setMinimumSize(QtCore.QSize(572, 524))
        self.mainBodyContent.setObjectName("mainBodyContent")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.mainBodyContent)
        self.horizontalLayout_4.setContentsMargins(0, 3, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.mainContentsContainer = QtWidgets.QWidget(parent=self.mainBodyContent)
        self.mainContentsContainer.setObjectName("mainContentsContainer")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.mainContentsContainer)
        self.verticalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_30.setSpacing(0)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.mainPages = QCustomStackedWidget(parent=self.mainContentsContainer)
        self.mainPages.setObjectName("mainPages")
        self.page_15 = QtWidgets.QWidget()
        self.page_15.setObjectName("page_15")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.page_15)
        self.verticalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.frame_18 = QtWidgets.QFrame(parent=self.page_15)
        self.frame_18.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_39 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.openFolderHome = QtWidgets.QPushButton(parent=self.frame_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openFolderHome.sizePolicy().hasHeightForWidth())
        self.openFolderHome.setSizePolicy(sizePolicy)
        self.openFolderHome.setMinimumSize(QtCore.QSize(200, 0))
        self.openFolderHome.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.openFolderHome.setFont(font)
        self.openFolderHome.setStyleSheet("#openFolderHome {\n"
"    background: #8680A6;\n"
"    border-radius: 4px;\n"
"    padding: 4px;\n"
"}\n"
"#openFolderHome::hover {\n"
"    background: #9287c5;\n"
"}\n"
"")
        self.openFolderHome.setIcon(icon1)
        self.openFolderHome.setIconSize(QtCore.QSize(20, 20))
        self.openFolderHome.setObjectName("openFolderHome")
        self.verticalLayout_39.addWidget(self.openFolderHome, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.openFileHome = QtWidgets.QPushButton(parent=self.frame_18)
        self.openFileHome.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.openFileHome.setFont(font)
        self.openFileHome.setStyleSheet("#openFileHome {\n"
"    background: #8680A6;\n"
"    border-radius: 4px;\n"
"    padding: 4px;\n"
"}\n"
"#openFileHome::hover {\n"
"    background: #9287c5;\n"
"}\n"
"")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/Icons/file.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.openFileHome.setIcon(icon10)
        self.openFileHome.setIconSize(QtCore.QSize(20, 20))
        self.openFileHome.setObjectName("openFileHome")
        self.verticalLayout_39.addWidget(self.openFileHome, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.createNewFolderHome = QtWidgets.QPushButton(parent=self.frame_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createNewFolderHome.sizePolicy().hasHeightForWidth())
        self.createNewFolderHome.setSizePolicy(sizePolicy)
        self.createNewFolderHome.setMinimumSize(QtCore.QSize(200, 0))
        self.createNewFolderHome.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.createNewFolderHome.setFont(font)
        self.createNewFolderHome.setStyleSheet("#createNewFolderHome {\n"
"    background: #8680A6;\n"
"    border-radius: 4px;\n"
"    padding: 4px;\n"
"}\n"
"#createNewFolderHome::hover {\n"
"    background: #9287c5;\n"
"}\n"
"")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/Icons/folder-plus.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.createNewFolderHome.setIcon(icon11)
        self.createNewFolderHome.setIconSize(QtCore.QSize(20, 20))
        self.createNewFolderHome.setObjectName("createNewFolderHome")
        self.verticalLayout_39.addWidget(self.createNewFolderHome, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.createNewFileHome = QtWidgets.QPushButton(parent=self.frame_18)
        self.createNewFileHome.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.createNewFileHome.setFont(font)
        self.createNewFileHome.setStyleSheet("#createNewFileHome {\n"
"    background: #8680A6;\n"
"    border-radius: 4px;\n"
"    padding: 4px;\n"
"}\n"
"#createNewFileHome::hover {\n"
"    background: #9287c5;\n"
"}")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/Icons/file-plus.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.createNewFileHome.setIcon(icon12)
        self.createNewFileHome.setIconSize(QtCore.QSize(20, 20))
        self.createNewFileHome.setObjectName("createNewFileHome")
        self.verticalLayout_39.addWidget(self.createNewFileHome, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_31.addWidget(self.frame_18)
        self.mainPages.addWidget(self.page_15)
        self.page_16 = QtWidgets.QWidget()
        self.page_16.setObjectName("page_16")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.page_16)
        self.verticalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.page_16)
        self.tabWidget.setIconSize(QtCore.QSize(10, 10))
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.verticalLayout_33.addWidget(self.tabWidget)
        self.mainPages.addWidget(self.page_16)
        self.page_17 = QtWidgets.QWidget()
        self.page_17.setObjectName("page_17")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.page_17)
        self.verticalLayout_34.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.label_20 = QtWidgets.QLabel(parent=self.page_17)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_34.addWidget(self.label_20)
        self.mainPages.addWidget(self.page_17)
        self.verticalLayout_30.addWidget(self.mainPages)
        self.horizontalLayout_4.addWidget(self.mainContentsContainer)
        self.minRightMenuContainer = QCustomSlideMenu(parent=self.mainBodyContent)
        self.minRightMenuContainer.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minRightMenuContainer.sizePolicy().hasHeightForWidth())
        self.minRightMenuContainer.setSizePolicy(sizePolicy)
        self.minRightMenuContainer.setMinimumSize(QtCore.QSize(0, 0))
        self.minRightMenuContainer.setMaximumSize(QtCore.QSize(50, 16777215))
        self.minRightMenuContainer.setObjectName("minRightMenuContainer")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.minRightMenuContainer)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setSpacing(0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.minRightMenuSubContainer = QtWidgets.QWidget(parent=self.minRightMenuContainer)
        self.minRightMenuSubContainer.setMinimumSize(QtCore.QSize(0, 0))
        self.minRightMenuSubContainer.setObjectName("minRightMenuSubContainer")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.minRightMenuSubContainer)
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setSpacing(0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.frame_6 = QtWidgets.QFrame(parent=self.minRightMenuSubContainer)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_26.setSpacing(10)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.maxRightMenuBtn = QtWidgets.QPushButton(parent=self.frame_6)
        self.maxRightMenuBtn.setText("")
        self.maxRightMenuBtn.setIcon(icon6)
        self.maxRightMenuBtn.setIconSize(QtCore.QSize(24, 24))
        self.maxRightMenuBtn.setObjectName("maxRightMenuBtn")
        self.verticalLayout_26.addWidget(self.maxRightMenuBtn)
        self.closeMinRightMenuBtn = QtWidgets.QPushButton(parent=self.frame_6)
        self.closeMinRightMenuBtn.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/Icons/window_close.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.closeMinRightMenuBtn.setIcon(icon13)
        self.closeMinRightMenuBtn.setIconSize(QtCore.QSize(16, 16))
        self.closeMinRightMenuBtn.setObjectName("closeMinRightMenuBtn")
        self.verticalLayout_26.addWidget(self.closeMinRightMenuBtn)
        self.openPerformanceMonitorMinBtn = QtWidgets.QPushButton(parent=self.frame_6)
        self.openPerformanceMonitorMinBtn.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/Icons/activity.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.openPerformanceMonitorMinBtn.setIcon(icon14)
        self.openPerformanceMonitorMinBtn.setIconSize(QtCore.QSize(24, 24))
        self.openPerformanceMonitorMinBtn.setObjectName("openPerformanceMonitorMinBtn")
        self.verticalLayout_26.addWidget(self.openPerformanceMonitorMinBtn)
        self.minTerminalPages = QCustomStackedWidget(parent=self.frame_6)
        self.minTerminalPages.setObjectName("minTerminalPages")
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.page_9)
        self.verticalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.label_18 = QtWidgets.QLabel(parent=self.page_9)
        self.label_18.setMinimumSize(QtCore.QSize(24, 24))
        self.label_18.setMaximumSize(QtCore.QSize(15, 14))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap(":/icons/Icons/life-buoy.png"))
        self.label_18.setScaledContents(True)
        self.label_18.setWordWrap(True)
        self.label_18.setIndent(0)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_29.addWidget(self.label_18, 0, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.minTerminalPages.addWidget(self.page_9)
        self.page_14 = QtWidgets.QWidget()
        self.page_14.setObjectName("page_14")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.page_14)
        self.verticalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.label_21 = QtWidgets.QLabel(parent=self.page_14)
        self.label_21.setMinimumSize(QtCore.QSize(24, 24))
        self.label_21.setMaximumSize(QtCore.QSize(15, 14))
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap(":/icons/Icons/corner-up-right.png"))
        self.label_21.setScaledContents(True)
        self.label_21.setWordWrap(True)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_32.addWidget(self.label_21, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.minTerminalPages.addWidget(self.page_14)
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.page_10)
        self.verticalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.label_14 = QtWidgets.QLabel(parent=self.page_10)
        self.label_14.setMinimumSize(QtCore.QSize(24, 24))
        self.label_14.setMaximumSize(QtCore.QSize(15, 14))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap(":/icons/Icons/terminal.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_27.addWidget(self.label_14, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.minTerminalPages.addWidget(self.page_10)
        self.verticalLayout_26.addWidget(self.minTerminalPages, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.verticalLayout_25.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(parent=self.minRightMenuSubContainer)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 200))
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_28.setContentsMargins(5, -1, 6, -1)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.label_16 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_16.setWordWrap(True)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_28.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_17.setWordWrap(True)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_28.addWidget(self.label_17)
        self.verticalLayout_25.addWidget(self.frame_7)
        self.verticalLayout_24.addWidget(self.minRightMenuSubContainer)
        self.horizontalLayout_4.addWidget(self.minRightMenuContainer, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.rightMenuContainer = QCustomSlideMenu(parent=self.mainBodyContent)
        self.rightMenuContainer.setMinimumSize(QtCore.QSize(200, 0))
        self.rightMenuContainer.setMaximumSize(QtCore.QSize(200, 16777215))
        self.rightMenuContainer.setObjectName("rightMenuContainer")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.rightMenuContainer)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.rightMenuSubContainer = QtWidgets.QWidget(parent=self.rightMenuContainer)
        self.rightMenuSubContainer.setMinimumSize(QtCore.QSize(200, 0))
        self.rightMenuSubContainer.setObjectName("rightMenuSubContainer")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.rightMenuSubContainer)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.frame_5 = QtWidgets.QFrame(parent=self.rightMenuSubContainer)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_5.setContentsMargins(3, -1, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.viewOptionsBox = QtWidgets.QComboBox(parent=self.frame_5)
        self.viewOptionsBox.setStyleSheet("#viewOptionsBox{\n"
"    background-color: #8680A6;\n"
"    border: 1px #8680A6;\n"
"    border-radius: 4px;\n"
"}\n"
"#viewOptionsBox::hover{\n"
"    background-color: #9287c5;\n"
"}\n"
"#viewOptionsBox::on {\n"
"    background-color: #9287c5;\n"
"}\n"
"\n"
"#viewOptionsBox QListView {\n"
"    background-color: #2D2E2E;\n"
"    \n"
"}\n"
"#viewOptionsBox QListView:item {\n"
"    border: 1px solid transparent; /* reserve space for selection border */\n"
"    \n"
"}\n"
"#viewOptionsBox QListView:item:hover {\n"
"    background: #606390;\n"
"    border-radius: 2px;\n"
"    \n"
"}\n"
"#viewOptionsBox::down-arrow {\n"
"    image: none;\n"
"}\n"
"#viewOptionsBox::drop-down { \n"
"                      subcontrol-origin: padding; \n"
"                      subcontrol-position: top right; \n"
"                      width: 15px; \n"
"                      border-left-width: 1px; \n"
"                      border-left-color: transparent; \n"
"                      border-left-style: solid; /* just a single line */\n"
"                      border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"                      border-bottom-right-radius: 3px; \n"
"}\n"
"")
        self.viewOptionsBox.setObjectName("viewOptionsBox")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icons/Icons/terminal.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.viewOptionsBox.addItem(icon15, "")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icons/Icons/corner-up-right.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.viewOptionsBox.addItem(icon16, "")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/icons/Icons/life-buoy.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.viewOptionsBox.addItem(icon17, "")
        self.horizontalLayout_5.addWidget(self.viewOptionsBox, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.openPerformanceMonitorBtn = QtWidgets.QPushButton(parent=self.frame_5)
        self.openPerformanceMonitorBtn.setText("")
        self.openPerformanceMonitorBtn.setIcon(icon14)
        self.openPerformanceMonitorBtn.setIconSize(QtCore.QSize(24, 24))
        self.openPerformanceMonitorBtn.setCheckable(True)
        self.openPerformanceMonitorBtn.setObjectName("openPerformanceMonitorBtn")
        self.horizontalLayout_5.addWidget(self.openPerformanceMonitorBtn, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.closeRightMenuBtn = QtWidgets.QPushButton(parent=self.frame_5)
        self.closeRightMenuBtn.setText("")
        self.closeRightMenuBtn.setIcon(icon13)
        self.closeRightMenuBtn.setObjectName("closeRightMenuBtn")
        self.horizontalLayout_5.addWidget(self.closeRightMenuBtn, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.minRightMenuBtn = QtWidgets.QPushButton(parent=self.frame_5)
        self.minRightMenuBtn.setText("")
        self.minRightMenuBtn.setIcon(icon5)
        self.minRightMenuBtn.setIconSize(QtCore.QSize(24, 24))
        self.minRightMenuBtn.setObjectName("minRightMenuBtn")
        self.horizontalLayout_5.addWidget(self.minRightMenuBtn, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.verticalLayout_19.addWidget(self.frame_5)
        self.terminalPages = QCustomStackedWidget(parent=self.rightMenuSubContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.terminalPages.sizePolicy().hasHeightForWidth())
        self.terminalPages.setSizePolicy(sizePolicy)
        self.terminalPages.setObjectName("terminalPages")
        self.page_11 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_11.sizePolicy().hasHeightForWidth())
        self.page_11.setSizePolicy(sizePolicy)
        self.page_11.setObjectName("page_11")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.page_11)
        self.verticalLayout_20.setContentsMargins(2, 2, 2, 10)
        self.verticalLayout_20.setSpacing(3)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.terminalFrame = QtWidgets.QFrame(parent=self.page_11)
        self.terminalFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.terminalFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.terminalFrame.setObjectName("terminalFrame")
        self.verticalLayout_49 = QtWidgets.QVBoxLayout(self.terminalFrame)
        self.verticalLayout_49.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_49.setSpacing(0)
        self.verticalLayout_49.setObjectName("verticalLayout_49")
        self.terminalBrowser = QtWidgets.QTextBrowser(parent=self.terminalFrame)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.terminalBrowser.setFont(font)
        self.terminalBrowser.setObjectName("terminalBrowser")
        self.verticalLayout_49.addWidget(self.terminalBrowser)
        self.verticalLayout_20.addWidget(self.terminalFrame)
        self.terminalInputFrame = QtWidgets.QFrame(parent=self.page_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.terminalInputFrame.sizePolicy().hasHeightForWidth())
        self.terminalInputFrame.setSizePolicy(sizePolicy)
        self.terminalInputFrame.setMinimumSize(QtCore.QSize(0, 20))
        self.terminalInputFrame.setMaximumSize(QtCore.QSize(16777215, 25))
        self.terminalInputFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.terminalInputFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.terminalInputFrame.setObjectName("terminalInputFrame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.terminalInputFrame)
        self.horizontalLayout_8.setContentsMargins(3, 0, 3, 1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.terminalInput = QtWidgets.QLineEdit(parent=self.terminalInputFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.terminalInput.sizePolicy().hasHeightForWidth())
        self.terminalInput.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.terminalInput.setFont(font)
        self.terminalInput.setInputMask("")
        self.terminalInput.setText("")
        self.terminalInput.setObjectName("terminalInput")
        self.horizontalLayout_8.addWidget(self.terminalInput)
        self.verticalLayout_20.addWidget(self.terminalInputFrame)
        self.terminalPages.addWidget(self.page_11)
        self.page_12 = QtWidgets.QWidget()
        self.page_12.setObjectName("page_12")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.page_12)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_11 = QtWidgets.QLabel(parent=self.page_12)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_21.addWidget(self.label_11)
        self.terminalPages.addWidget(self.page_12)
        self.page_13 = QtWidgets.QWidget()
        self.page_13.setObjectName("page_13")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.page_13)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_12 = QtWidgets.QLabel(parent=self.page_13)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_22.addWidget(self.label_12)
        self.terminalPages.addWidget(self.page_13)
        self.verticalLayout_19.addWidget(self.terminalPages)
        self.widget_2 = QCustomSlideMenu(parent=self.rightMenuSubContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMaximumSize(QtCore.QSize(200, 200))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setSpacing(0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.frame_19 = QtWidgets.QFrame(parent=self.widget_2)
        self.frame_19.setMinimumSize(QtCore.QSize(0, 200))
        self.frame_19.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_40 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_40.setContentsMargins(0, 0, 3, 3)
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.cpuContainer = QtWidgets.QFrame(parent=self.frame_19)
        self.cpuContainer.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.cpuContainer.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.cpuContainer.setObjectName("cpuContainer")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.cpuContainer)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.cpuLabel = QtWidgets.QFrame(parent=self.cpuContainer)
        self.cpuLabel.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.cpuLabel.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.cpuLabel.setObjectName("cpuLabel")
        self.verticalLayout_41 = QtWidgets.QVBoxLayout(self.cpuLabel)
        self.verticalLayout_41.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        self.label_4 = QtWidgets.QLabel(parent=self.cpuLabel)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_41.addWidget(self.label_4)
        self.horizontalLayout_9.addWidget(self.cpuLabel)
        self.cpuProgress = roundProgressBar(parent=self.cpuContainer)
        self.cpuProgress.setObjectName("cpuProgress")
        self.horizontalLayout_9.addWidget(self.cpuProgress)
        self.verticalLayout_40.addWidget(self.cpuContainer)
        self.ramContainer = QtWidgets.QFrame(parent=self.frame_19)
        self.ramContainer.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.ramContainer.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.ramContainer.setObjectName("ramContainer")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.ramContainer)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.ramLabel = QtWidgets.QFrame(parent=self.ramContainer)
        self.ramLabel.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.ramLabel.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.ramLabel.setObjectName("ramLabel")
        self.verticalLayout_42 = QtWidgets.QVBoxLayout(self.ramLabel)
        self.verticalLayout_42.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.label_6 = QtWidgets.QLabel(parent=self.ramLabel)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_42.addWidget(self.label_6)
        self.horizontalLayout_10.addWidget(self.ramLabel)
        self.ramProgress = roundProgressBar(parent=self.ramContainer)
        self.ramProgress.setObjectName("ramProgress")
        self.horizontalLayout_10.addWidget(self.ramProgress)
        self.verticalLayout_40.addWidget(self.ramContainer)
        self.gpuContainer = QtWidgets.QFrame(parent=self.frame_19)
        self.gpuContainer.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.gpuContainer.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.gpuContainer.setObjectName("gpuContainer")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.gpuContainer)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.gpuLabel = QtWidgets.QFrame(parent=self.gpuContainer)
        self.gpuLabel.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.gpuLabel.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.gpuLabel.setObjectName("gpuLabel")
        self.verticalLayout_43 = QtWidgets.QVBoxLayout(self.gpuLabel)
        self.verticalLayout_43.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_43.setObjectName("verticalLayout_43")
        self.label_9 = QtWidgets.QLabel(parent=self.gpuLabel)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_43.addWidget(self.label_9)
        self.horizontalLayout_11.addWidget(self.gpuLabel)
        self.gpuProgress = roundProgressBar(parent=self.gpuContainer)
        self.gpuProgress.setObjectName("gpuProgress")
        self.horizontalLayout_11.addWidget(self.gpuProgress)
        self.memProgress = roundProgressBar(parent=self.gpuContainer)
        self.memProgress.setObjectName("memProgress")
        self.horizontalLayout_11.addWidget(self.memProgress)
        self.verticalLayout_40.addWidget(self.gpuContainer)
        self.verticalLayout_23.addWidget(self.frame_19)
        self.verticalLayout_19.addWidget(self.widget_2)
        self.verticalLayout_18.addWidget(self.rightMenuSubContainer)
        self.horizontalLayout_4.addWidget(self.rightMenuContainer, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.verticalLayout_8.addWidget(self.mainBodyContent)
        self.horizontalLayout.addWidget(self.mainBodyContainer)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 900, 36))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.menuBar.setFont(font)
        self.menuBar.setAcceptDrops(True)
        self.menuBar.setAutoFillBackground(False)
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(parent=self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuOpen_Recent = QtWidgets.QMenu(parent=self.menuFile)
        self.menuOpen_Recent.setObjectName("menuOpen_Recent")
        self.menuEdit = QtWidgets.QMenu(parent=self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuWindow = QtWidgets.QMenu(parent=self.menuBar)
        self.menuWindow.setObjectName("menuWindow")
        MainWindow.setMenuBar(self.menuBar)
        self.actionNew_File = QtGui.QAction(parent=MainWindow)
        self.actionNew_File.setObjectName("actionNew_File")
        self.actionNew_Folder = QtGui.QAction(parent=MainWindow)
        self.actionNew_Folder.setObjectName("actionNew_Folder")
        self.actionNew_Text_File = QtGui.QAction(parent=MainWindow)
        self.actionNew_Text_File.setObjectName("actionNew_Text_File")
        self.actionNew_Project = QtGui.QAction(parent=MainWindow)
        self.actionNew_Project.setObjectName("actionNew_Project")
        self.actionOpen_File = QtGui.QAction(parent=MainWindow)
        self.actionOpen_File.setObjectName("actionOpen_File")
        self.actionOpen_Folder = QtGui.QAction(parent=MainWindow)
        self.actionOpen_Folder.setObjectName("actionOpen_Folder")
        self.actionSave = QtGui.QAction(parent=MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtGui.QAction(parent=MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.action_File_Here = QtGui.QAction(parent=MainWindow)
        self.action_File_Here.setObjectName("action_File_Here")
        self.actionUndo = QtGui.QAction(parent=MainWindow)
        self.actionUndo.setVisible(True)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtGui.QAction(parent=MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionCut = QtGui.QAction(parent=MainWindow)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtGui.QAction(parent=MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtGui.QAction(parent=MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionOpen_Terminal = QtGui.QAction(parent=MainWindow)
        self.actionOpen_Terminal.setObjectName("actionOpen_Terminal")
        self.actionOpen_Editor = QtGui.QAction(parent=MainWindow)
        self.actionOpen_Editor.setObjectName("actionOpen_Editor")
        self.actionOpen_Monitor = QtGui.QAction(parent=MainWindow)
        self.actionOpen_Monitor.setObjectName("actionOpen_Monitor")
        self.menuOpen_Recent.addAction(self.action_File_Here)
        self.menuFile.addAction(self.actionNew_File)
        self.menuFile.addAction(self.actionNew_Folder)
        self.menuFile.addAction(self.actionNew_Text_File)
        self.menuFile.addAction(self.actionNew_Project)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen_File)
        self.menuFile.addAction(self.actionOpen_Folder)
        self.menuFile.addAction(self.menuOpen_Recent.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuWindow.addAction(self.actionOpen_Terminal)
        self.menuWindow.addAction(self.actionOpen_Editor)
        self.menuWindow.addAction(self.actionOpen_Monitor)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuWindow.menuAction())

        self.retranslateUi(MainWindow)
        self.minCenterMenuPages.setCurrentIndex(1)
        self.centerMenuLabels.setCurrentIndex(0)
        self.centerMenuPages.setCurrentIndex(1)
        self.mainPages.setCurrentIndex(0)
        self.minTerminalPages.setCurrentIndex(2)
        self.terminalPages.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.homeBtn.setToolTip(_translate("MainWindow", "Home"))
        self.fileBtn.setToolTip(_translate("MainWindow", "File Explorer"))
        self.searchBtn.setToolTip(_translate("MainWindow", "Search"))
        self.aiBtn.setToolTip(_translate("MainWindow", "AI Assistant"))
        self.settingsBtn.setToolTip(_translate("MainWindow", "Settings"))
        self.maxCenterMenuBtn.setToolTip(_translate("MainWindow", "Maximize"))
        self.label_5.setText(_translate("MainWindow", "S e t t i n g s - M i n"))
        self.label.setText(_translate("MainWindow", "Auto Completion Length"))
        self.TextToText.setItemText(0, _translate("MainWindow", "Normal"))
        self.TextToText.setItemText(1, _translate("MainWindow", "Short"))
        self.TextToText.setItemText(2, _translate("MainWindow", "Medium"))
        self.TextToText.setItemText(3, _translate("MainWindow", "Long"))
        self.label_2.setText(_translate("MainWindow", "Auto Doc Length"))
        self.CodeToCode.setItemText(0, _translate("MainWindow", "Normal"))
        self.CodeToCode.setItemText(1, _translate("MainWindow", "Short"))
        self.CodeToCode.setItemText(2, _translate("MainWindow", "Medium"))
        self.CodeToCode.setItemText(3, _translate("MainWindow", "Long"))
        self.label_3.setText(_translate("MainWindow", "Code Generation Length"))
        self.Summerize.setItemText(0, _translate("MainWindow", "Normal"))
        self.Summerize.setItemText(1, _translate("MainWindow", "Short"))
        self.Summerize.setItemText(2, _translate("MainWindow", "Medium"))
        self.Summerize.setItemText(3, _translate("MainWindow", "Long"))
        self.label_7.setText(_translate("MainWindow", "S e a r c h - M i n"))
        self.label_8.setText(_translate("MainWindow", "F i  l e - E x p l o r e r - M i n"))
        self.label_19.setText(_translate("MainWindow", "File Explorer"))
        self.label_22.setText(_translate("MainWindow", "Search"))
        self.label_23.setText(_translate("MainWindow", "AI Assistant"))
        self.label_24.setText(_translate("MainWindow", "Settings"))
        self.minCenterMenuBtn.setToolTip(_translate("MainWindow", "Minimize"))
        self.settingsDescription.setText(_translate("MainWindow", "Manage themes and preferences"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Ask something..."))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Search"))
        self.checkBox.setText(_translate("MainWindow", "Search in modules"))
        self.openFolderHome.setText(_translate("MainWindow", "Open Folder"))
        self.openFileHome.setText(_translate("MainWindow", "Open File"))
        self.createNewFolderHome.setText(_translate("MainWindow", "Create New Folder"))
        self.createNewFileHome.setText(_translate("MainWindow", "Create New File"))
        self.label_20.setText(_translate("MainWindow", "More Settings"))
        self.maxRightMenuBtn.setToolTip(_translate("MainWindow", "Maximize"))
        self.closeMinRightMenuBtn.setToolTip(_translate("MainWindow", "Close"))
        self.label_16.setText(_translate("MainWindow", "CPU: 15%"))
        self.label_17.setText(_translate("MainWindow", "RAM: 33%"))
        self.viewOptionsBox.setItemText(0, _translate("MainWindow", "Terminal"))
        self.viewOptionsBox.setItemText(1, _translate("MainWindow", "Output"))
        self.viewOptionsBox.setItemText(2, _translate("MainWindow", "Debug"))
        self.openPerformanceMonitorBtn.setToolTip(_translate("MainWindow", "Performance monitor"))
        self.closeRightMenuBtn.setToolTip(_translate("MainWindow", "Close"))
        self.minRightMenuBtn.setToolTip(_translate("MainWindow", "Minimize"))
        self.terminalInput.setPlaceholderText(_translate("MainWindow", "Replace..."))
        self.label_11.setText(_translate("MainWindow", "Output"))
        self.label_12.setText(_translate("MainWindow", "Debug"))
        self.label_4.setText(_translate("MainWindow", "CPU Utilization"))
        self.label_6.setText(_translate("MainWindow", "RAM Utilization"))
        self.label_9.setText(_translate("MainWindow", "GPU Utilization & Memory"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuOpen_Recent.setTitle(_translate("MainWindow", "Open Recent"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuWindow.setTitle(_translate("MainWindow", "Window"))
        self.actionNew_File.setText(_translate("MainWindow", "New File..."))
        self.actionNew_Folder.setText(_translate("MainWindow", "New Folder..."))
        self.actionNew_Text_File.setText(_translate("MainWindow", "New Text File..."))
        self.actionNew_Project.setText(_translate("MainWindow", "New Project..."))
        self.actionOpen_File.setText(_translate("MainWindow", "Open File..."))
        self.actionOpen_Folder.setText(_translate("MainWindow", "Open Folder..."))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As..."))
        self.action_File_Here.setText(_translate("MainWindow", "[File Here]"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionCut.setText(_translate("MainWindow", "Cut"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionOpen_Terminal.setText(_translate("MainWindow", "Open Terminal"))
        self.actionOpen_Editor.setText(_translate("MainWindow", "Open Editor"))
        self.actionOpen_Monitor.setText(_translate("MainWindow", "Open Monitor"))
from Custom_Widgets.Widgets import QCustomSlideMenu, QCustomStackedWidget
from Custom_Widgets.RoundProgressBar import roundProgressBar
